terraform import google_compute_target_https_proxy.terraform-target-proxy-https compute.googleapis.com/projects/infra-actor-333516/global/targetHttpsProxies/terraform-load-balancer-target-proxy-2
terraform import google_compute_ssl_certificate.terraform-cert compute.googleapis.com/projects/infra-actor-333516/global/sslCertificates/terraform-cert
terraform import google_compute_router.terraform-nat-router compute.googleapis.com/projects/infra-actor-333516/regions/europe-central2/routers/terraform-nat-router
terraform import google_compute_target_http_proxy.terraform-target-proxy-http compute.googleapis.com/projects/infra-actor-333516/global/targetHttpProxies/terraform-load-balancer-target-proxy
terraform import google_compute_url_map.terraform-url-map compute.googleapis.com/projects/infra-actor-333516/global/urlMaps/terraform-load-balancer
terraform import google_compute_backend_service.terraform-backend compute.googleapis.com/projects/infra-actor-333516/global/backendServices/terraform-backend
terraform import google_compute_health_check.terraform-health-check compute.googleapis.com/projects/infra-actor-333516/global/healthChecks/terraform-health-check
terraform import google_compute_address.nat-auto-ip compute.googleapis.com/projects/infra-actor-333516/regions/europe-central2/addresses/nat-auto-ip-1779784-8-1641304357129320
terraform import google_compute_global_forwarding_rule.terraform-load-balancer-forwarding-rule compute.googleapis.com/projects/infra-actor-333516/global/forwardingRules/terraform-load-balancer-forwarding-rule
terraform import google_compute_global_forwarding_rule.https compute.googleapis.com/projects/infra-actor-333516/global/forwardingRules/https
